# BuildKit micro TOML config
[worker.oci]
enabled = true
platforms = ["linux/amd64"]
snapshotter = "overlayfs"
rootless = false
noProcessSandbox = true

[grpc]
address = ["tcp://0.0.0.0:1234"]

[cache]
maxAge = "48h"
maxSize = "2GB"

[experimental]
enabled = true
