services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - mcr.microsoft.com/devcontainers/base:bullseye
    image: dind-javascript-dev:latest
    container_name: dind-javascript-devcontainer
    privileged: true
    restart: unless-stopped
    
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - dind-var-lib-docker:/var/lib/docker
      - dind-buildkit-cache:/cache/buildkit
      - dind-docker-cache:/cache/docker
      - dind-npm-cache:/cache/npm
      - dind-yarn-cache:/cache/yarn
      - dind-node-modules:/workspace/node_modules
      - dind-tmp:/tmp:cached
    
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock
      - BUILDKIT_HOST=docker-container://buildkit
      - DOCKER_BUILDKIT=1
      - COMPOSE_DOCKER_CLI_BUILD=1
      - NPM_CONFIG_CACHE=/cache/npm
      - YARN_CACHE_FOLDER=/cache/yarn
      - NODE_ENV=development
    
    networks:
      - devcontainer-network
    
    command: sleep infinity

  buildkit:
    image: moby/buildkit:latest
    container_name: dind-buildkit
    privileged: true
    restart: unless-stopped
    volumes:
      - dind-buildkit-cache:/var/lib/buildkit
    networks:
      - devcontainer-network

volumes:
  dind-var-lib-docker:
    driver: local
  dind-buildkit-cache:
    driver: local
  dind-docker-cache:
    driver: local
  dind-npm-cache:
    driver: local
  dind-yarn-cache:
    driver: local
  dind-node-modules:
    driver: local
  dind-tmp:
    driver: local

networks:
  devcontainer-network:
    driver: bridge
