# syntax=docker/dockerfile:1.8
FROM registry:2

COPY ../../config/micro/registry-config.micro.yml /etc/docker/registry/config.yml

HEALTHCHECK --interval=15s --timeout=5s --retries=2 --start-period=10s \
  CMD wget --quiet --tries=1 --spider http://localhost:5000/v2/ || exit 1

CMD ["registry", "serve", "/etc/docker/registry/config.yml"]
