# syntax=docker/dockerfile:1.8
FROM moby/buildkit:latest

# Use TOML for config
COPY ../../config/micro/buildkitd.micro.toml /etc/buildkit/buildkitd.toml

HEALTHCHECK --interval=15s --timeout=5s --retries=2 --start-period=10s \
  CMD buildctl debug workers | grep -q 'org.mobyproject.buildkit.worker.executor' || exit 1

CMD ["buildkitd", "--config", "/etc/buildkit/buildkitd.toml"]
