# syntax=docker/dockerfile:1.8
FROM redis:7-alpine

COPY ../../config/micro/redis.micro.conf /usr/local/etc/redis/redis.conf

HEALTHCHECK --interval=5s --timeout=2s --retries=2 --start-period=5s \
  CMD redis-cli ping | grep -q PONG || exit 1

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
