version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: dind-micro-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ../../config/micro/postgresql.micro.conf:/usr/local/share/postgresql/postgresql.conf.sample:ro
    networks:
      - devcontainer-network
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    env_file:
      - ../../config/micro/performance.micro.env
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'devuser', '-d', 'devdb', '-h', 'localhost']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  devcontainer-network:
    driver: bridge
