version: '3.9'
services:
  redis:
    image: redis:7-alpine
    container_name: dind-micro-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ../../config/micro/redis.micro.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - devcontainer-network
    environment:
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  devcontainer-network:
    driver: bridge
