services:
  devcontainer:
    environment:
      - DEBUG=*
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ../../../logs:/workspace/logs:cached
    command: >
      bash -c "
        echo 'Starting development environment...' &&
        sleep infinity
      "

  buildkit:
    environment:
      - BUILDKIT_DEBUG=1
    command: >
      buildkitd
      --debug
      --oci-worker-no-process-sandbox
      --allow-insecure-entitlement security.insecure
      --allow-insecure-entitlement network.host

  redis:
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --loglevel debug
      --save 60 1

  postgres:
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    command: >
      postgres
      -c log_statement=all
      -c log_min_duration_statement=0
      -c shared_preload_libraries=pg_stat_statements
